# Site
repository: sainaath-r/sainaath.github.io

# Personal info
name: Sainaath Ramanathan
title: Cloud Solutions Architect
email: sainaath.ramanathan@hotmail.com
website: sainaath-r.github.io

## Dark Mode
darkmode: true

# Social links
github_username:  sainaath-r
linkedin_username: sainaathramanathan

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
